apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: rmc3408/microservice-ticket-auth
          env:
            - name: JWTKEY
              value: Secret@123
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
