apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: rmc3408/microservice-ticket-order
          env:
            - name: MONGO_URI
              value: mongodb://order-mongo-srv:27017/order
            - name: PORT_ORDER
              value: '4002'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticket-nats
            - name: JWTKEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWTKEY
---
apiVersion: v1
kind: Service
metadata:
  name: order-srv
spec:
  type: LoadBalancer
  selector:
    app: order
  ports:
    - name: order
      protocol: TCP
      port: 4002
      targetPort: 4002