apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator
  template:
    metadata:
      labels:
        app: moderator
    spec:
      containers:
        - name: moderator
          image: moderator-microservice:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: moderator-srv
spec:
  type: NodePort
  selector:
    app: moderator
  ports:
    - name: moderator
      protocol: TCP
      port: 5001
      targetPort: 5001